[book]
authors = ["Noni"]
language = "ko-kr"
title = "phycis_noni"
[output.html]
mathjax-support = true
git-repository-url = "https://github.com/ojc1234/physcis_noni"
edit-url-template = "https://github.com/ojc1234/physcis_noni/blob/master/{path}"